{{- /*
Same as image-pull-secret.yaml. We need to put a copy of that secret into the Argo CD namespace. It seems that Argo CD cannot access secrets in other namespaces.
*/ -}}
{{- if .Values.argoCd.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watch.argoCdImagePullSecretName" . }}
  namespace: {{ .Values.argoCd.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "watch.imagePullSecretData" . }}
{{- end -}}
