{{- range .Values.djangoCronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .schedule }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "django.serviceAccountName" $ }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          initContainers:
            - name: wait-for-django
              image: bitnami/kubectl
              imagePullPolicy: IfNotPresent
              args:
                - wait
                - deployments/{{ include "django.fullname" $ }}
                - --for=condition=available
                - --timeout=300s
          containers:
            - name: {{ .name }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command: ["/bin/sh"]
              args:
                  - -c
                  - >-
                      {{ .command }}
              # TODO: Add liveness and readiness probes, e.g. https://github.com/celery/celery/issues/4079
              {{- include "django.envVariables" $ | nindent 14 }}
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              volumeMounts:
                {{- include "django.secretVolumeMounts" $ | nindent 16 }}

          volumes:
            {{- include "django.secretVolumes" $ | nindent 12 }}

          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
