---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-rolebinding
subjects:
- kind: ServiceAccount
  name: cronjob-serviceaccount
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: cronjob-role
  apiGroup: rbac.authorization.k8s.io
