{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.targets -}}
{{- range .Values.externalSecrets.targets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  target:
    name: {{ .name }}
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
    {{- if .template }}
    template:
      {{ .template | toYaml | nindent 6 }}
    {{- end }}
  {{- if .data }}
  data:
    {{ .data | toYaml | nindent 4 }}
  {{- end }}
  {{- if .dataFrom }}
  dataFrom:
    {{ .dataFrom | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
