{{- if .Values.dbMigrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django.fullname" . }}-db-migrations
  labels:
    {{- include "django.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- if .Values.dbMigrations.annotations }}
    {{- toYaml .Values.dbMigrations.annotations | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      annotations:
        {{- if .Values.dbMigrations.safeToEvict }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        {{- end }}
      labels:
        {{- include "django.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "django.fullname" . }}
    spec:
      restartPolicy: {{ .Values.dbMigrations.restartPolicy | default "OnFailure" }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      initContainers:
      {{- if .Values.db.cluster.create }}
        - name: wait-for-db
          image: bitnami/kubectl
          imagePullPolicy: IfNotPresent
          args:
            - wait
            - clusters.postgresql.cnpg.io/{{ include "django.dbClusterName" . }}
            - --for=condition=ready
            - --timeout=180s
      {{- end }}
      volumes:
        {{- include "django.secretVolumes" . | nindent 8 }}
      containers:
        - name: {{ .Values.dbMigrations.name | default "db-migrations" | quote}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- include "django.appImageConfig" . | nindent 10 }}
          resources:
            {{- toYaml .Values.dbMigrations.resources | nindent 12 }}
          volumeMounts:
            {{- include "django.secretVolumeMounts" . | nindent 12 }}
          command: ["/bin/sh"]
          args:
              - -c
              - >-
                  {{ .Values.dbMigrations.command }}
          {{- include "django.envVariables" . | nindent 10 }}
{{- end }}
