{{- if .Values.dbMigrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django.fullname" . }}-db-migrations
  labels:
    {{- include "django.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- if .Values.dbMigrations.annotations }}
    {{- toYaml .Values.dbMigrations.annotations | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      annotations:
        {{- if .Values.dbMigrations.safeToEvict }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        {{- end }}
      labels:
        {{- include "django.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "django.fullname" . }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      containers:
        - name: {{ .Values.dbMigrations.name | default "db-migrations" | quote}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.dbMigrations.resources | nindent 12 }}
          command: ["/bin/sh"]
          args:
              - -c
              - >-
                  {{ .Values.dbMigrations.command }}
          {{- if or .Values.envSecrets .Values.envConfigs }} 
          envFrom:
            {{- if .Values.envSecrets }}
            - secretRef:
                name: env-secrets
            {{- end }}
            {{- if .Values.envConfigs }}
            - configMapRef:
                name: env-configmap
            {{- end }}
          {{- end }}
{{- end }}
