{{- if .Values.db.cluster.scheduledBackup.create -}}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "django.dbScheduledBackupName" . }}
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: {{ include "django.dbClusterName" . }}
  # immediate: true  # may be useful for testing
{{- end -}}
