{{- if .Values.celery.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django.fullname" . }}-{{ .Values.celery.worker.componentName }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.celery.worker.componentName }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.celery.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "django.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.celery.worker.componentName }}
  strategy:
    type: {{ .Values.celery.worker.strategy }}
  template:
    metadata:
      labels:
        {{- include "django.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.celery.worker.componentName }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/env-configmap: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
        checksum/env-secrets: {{ include (print $.Template.BasePath "/env-secrets.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-django
          image: bitnami/kubectl
          imagePullPolicy: IfNotPresent
          args:
            - wait
            - deployments/{{ include "django.fullname" . }}
            - --for=condition=available
            - --timeout=300s
      containers:
        - name: celery-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{-  with .Values.celery.worker.command }}
          command: ["/bin/sh"]
          args:
              - -c
              - >-
                  {{ . }}
          {{- end }}
          # TODO: Add liveness and readiness probes, e.g. https://github.com/celery/celery/issues/4079
          {{- include "django.envVariables" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "django.secretVolumeMounts" . | nindent 12 }}

      volumes:
        {{- include "django.secretVolumes" . | nindent 8 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
